---
title: Sleep tracker
hero_image: images/banner.png
description: 
  Monitor your sleep to see how rested you are
version: 4
listed: true
copyedit: true
last_tested: '2023-08-18'
steps:
- title: You will make
- title: Track and display
  completion:
    - engaged
- title: Check your head
- title: Push to reset
- title: Change brightness
- title: Show some Zs
- title: 1,2,3, sleep!
  completion:
    - internal
- title: Quick quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
      - external
- title: Upgrade your project